---
services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DEV_NAME:-charity}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DEV_NAME:-charity}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: thegreatestgiant/obligo
    restart: unless-stopped
    environment:
      DB_URL: "postgres://${DB_USER:-user}:${DB_PASS:-password}@db:5432/${DEV_NAME:-charity}?sslmode=disable"
      JWT_SECRET: ${JWT_SECRET:-"your_actual_long_secret_string"}
      APP_PORT: ${APP_PORT:-1234}
      APP_URL: ${APP_URL:-"http://localhost:8080"}
    ports:
      - "8080:${APP_PORT:-1234}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
