---
services:
  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "${DEV_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DEV_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./adminer-autologin.php:/var/www/html/index.php
    environment:
      ADMINER_SERVER: db
      ADMINER_USER: ${DB_USER}
      ADMINER_PASSWORD: ${DB_PASS}
      ADMINER_DB: ${DEV_NAME}
