---
services:
  db-dev:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "${DEV_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DEV_NAME}

  db-test:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "${TEST_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${TEST_NAME}

  db-prod:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "${PROD_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${PROD_NAME}
    volumes:
      - pgdata-local:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata-local:
